/**
 * Banco de frases em português usado pelo motor de demonstração para montar
 * a transcrição simulada. Em produção, este texto vem do modelo de transcrição
 * (faster-whisper) aplicado ao áudio real.
 */
export const SENTENCES: string[] = [
  "Bom dia, obrigada por atender a minha ligação.",
  "Eu preciso confirmar alguns pontos da nossa conversa de ontem.",
  "Pois não, pode falar que eu estou anotando aqui.",
  "O pagamento foi combinado para o dia quinze, certo?",
  "Isso mesmo, ficou acertado no dia quinze de cada mês.",
  "Eu queria pedir um prazo maior para entregar o documento.",
  "Se for até sexta-feira, não vejo problema nenhum.",
  "Então combinamos assim, eu entrego até sexta ao meio-dia.",
  "Você recebeu o contrato que eu enviei por e-mail?",
  "Recebi sim, mas fiquei com uma dúvida na cláusula terceira.",
  "Aquela cláusula trata apenas da forma de pagamento.",
  "Entendi, então o valor continua o mesmo do orçamento.",
  "Exatamente, o valor não sofreu nenhum ajuste.",
  "Posso gravar esta conversa para meu controle pessoal?",
  "Pode gravar, eu não me importo.",
  "A reunião ficou marcada para quinta-feira às dez horas.",
  "Quinta às dez está bom para mim.",
  "Precisamos da assinatura das duas partes no documento.",
  "Eu assino hoje ainda e te envio a cópia digitalizada.",
  "O prazo de resposta termina na próxima segunda-feira.",
  "Então temos que resolver tudo até o fim de semana.",
  "Vou conversar com o advogado antes de dar a resposta final.",
  "Me parece uma atitude prudente.",
  "O áudio da outra ligação ficou com chiado no começo.",
  "Aqui do meu lado a gravação saiu limpa.",
  "Confere se o valor da parcela bate com o extrato.",
  "Bate sim, eu conferi linha por linha ontem à noite.",
  "A testemunha confirmou o horário do encontro.",
  "Ótimo, isso reforça o que estava escrito na ata.",
  "Eu guardei todas as mensagens trocadas naquele período.",
  "Se precisar, posso imprimir e levar no cartório.",
  "O cartório pediu apenas o reconhecimento de firma.",
  "Então é só levar o documento original e a identidade.",
  "A perícia deve sair em trinta dias, segundo o protocolo.",
  "Trinta dias é um prazo razoável, considerando o recesso.",
  "Vou protocolar o pedido ainda hoje no fim do expediente.",
  "Me avisa quando tiver o número do protocolo, por favor.",
  "Aviso sim, pode deixar comigo.",
  "Aquela conversa aconteceu na presença de duas pessoas.",
  "As duas podem confirmar o que foi dito.",
  "O importante é manter tudo registrado por escrito.",
  "Por isso eu prefiro formalizar por e-mail.",
  "Certo, então me envia um resumo do que combinamos.",
  "Envio ainda hoje, antes das seis horas.",
  "Qualquer novidade eu te retorno imediatamente.",
  "Combinado então, qualquer coisa estou à disposição.",
  "Ficou alguma pendência da última reunião?",
  "Só a questão do prazo, que acabamos de resolver agora.",
];
